[package]
name = "czkawka"
version = "0.1.0"
authors = ["Rafał Mikrut <mikrutrafal@protonmail.com>"]
edition = "2018"

[dependencies]
humansize = "1.1.0"
#rayon = "1.4.0"
blake3 = "0.3.6"
#regex = "1.3.9"