name: czkawka # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Czkawka - fast data cleaner written in Rust # 79 char long summary
description: |
  Czkawka is very fast and feature rich cleaner which finds file duplicates, empty folders and files, duplicated music, similar images or the biggest files in selected directories.
  This program have frontend written in modern GTK 3.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  czkawka:
    plugin: nil
    source: https://github.com/qarmin/czkawka.git
    source-tag: 1.5.1
    build-packages:
      - libgtk-3-dev
      - curl
      - gcc
      - git
    stage-packages:
      - libgtk-3-dev
    override-build: |
      if ! command -v rustup 2>/dev/null; then
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile=minimal
          export PATH="${HOME}/.cargo/bin:${PATH}"
      fi

      cargo install --locked --path czkawka_gui --root "${SNAPCRAFT_PART_INSTALL}" --force

apps:
  czkawka:
    command: bin/czkawka_gui
    extensions: [gnome-3-34]
    plugs:
      - home
      - removable-media
      - udisks2
